# ==============================================================================
# 🌌 MAIN GIT-MANAGED PROFILE (.bashrc)
# ==============================================================================

# Global paths for custom local application stacks
export PATH="$HOME/.npm-global/bin:$PATH"
export PATH="/usr/bin:$PATH"
export PATH="$HOME/.browseros/bin:$PATH"

# Managed Pro-Spec Internal Aliases Handshake
# (This line connects your system to the local engine generated by your init script)
[ -f ~/.bash_aliases_pro ] && source ~/.bash_aliases_pro
